### ISSUE TITLE
roombapw docker image won't install on RPI

### ISSUE THREAD

**Issue by TriskelionTech** [jeremywillans/hass-addons#1]
I was able to install the first two addons, but when I tried to install roombapw, it returned "The command '/bin/sh -c npm install' returned a non-zero code: 1"

**Comment by hcorn82** [comment]
Same issue here.

**Comment by jeremywillans** [comment]
What platform? @ZInventor @hcorn82

**Comment by TriskelionTech** [comment]
I'm running the homeassistant raspberry pi image on a Pi 3B v1.2

**Comment by Rev-777** [comment]
Supervisor 2020.12.1 is the same: The command '/bin/sh -c npm install' returned a non-zero code: 1

> 21-01-04 18:12:53 INFO (SyncWorker_0) [supervisor.docker.addon] Starting build for 39c40414/armv7-addon-roombapw:1.0.0
21-01-04 18:13:00 ERROR (SyncWorker_0) [supervisor.docker.addon] Can't build 39c40414/armv7-addon-roombapw:1.0.0: The command '/bin/sh -c npm install' returned a non-zero code: 1
21-01-04 18:13:00 ERROR (SyncWorker_0) [supervisor.docker.addon] Build log: 
Step 1/16 : FROM node:alpine
 ---> 33d134315a1e
Step 2/16 : RUN mkdir -p /usr/src/app
 ---> Using cache
 ---> cbbbd72dbdba
Step 3/16 : WORKDIR /usr/src/app
 ---> Using cache
 ---> 3c0e00c25084
Step 4/16 : ENV NODE_ENV production
 ---> Using cache
 ---> 52fd784f24d8
Step 5/16 : COPY package.json /usr/src/app/
 ---> Using cache
 ---> 00627fdef36b
Step 6/16 : RUN npm install
 ---> Running in 73edb884316f
npm
 ERR! 
code
 ERESOLVE

**Comment by pt0x** [comment]
same here, on  ubuntu server 20.10 and Ha 2020.12.7

21-01-04 20:19:05 ERROR (SyncWorker_4) [supervisor.docker.addon] Can't build 39c40414/amd64-addon-roombapw:1.0.0: The command '/bin/sh -c npm install' returned a non-zero code: 1
21-01-04 20:19:05 ERROR (SyncWorker_4) [supervisor.docker.addon] Build log: 
Step 1/16 : FROM node:alpine
 ---> 5304e0d27d98
Step 2/16 : RUN mkdir -p /usr/src/app
 ---> Running in 378abfe2adc4
Removing intermediate container 378abfe2adc4
 ---> a0560343d29d
Step 3/16 : WORKDIR /usr/src/app
 ---> Running in 8b1ab37529e3
Removing intermediate container 8b1ab37529e3
 ---> 9df2a32c1e49
Step 4/16 : ENV NODE_ENV production
 ---> Running in cb222059b76b
Removing intermediate container cb222059b76b
 ---> 635c7d01c393
Step 5/16 : COPY package.json /usr/src/app/
 ---> a537f40e76b3
Step 6/16 : RUN npm install
 ---> Running in 0e56866e7aaf
npm ERR! code ERESOLVE

npm ERR! Cannot destructure property 'name' of 'node' as it is null.


npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-04T20_19_04_959Z-debug.log

Removing intermediate container 0e56866e7aaf

**Comment by famprinz** [comment]
> I was able to install the first two addons, but when I tried to install roombapw, it returned "The command '/bin/sh -c npm install' returned a non-zero code: 1"

Same here - I have HA running on a NUC. "The command '/bin/sh -c npm install' returned a non-zero code: 1"

**Comment by famprinz** [comment]
> > I was able to install the first two addons, but when I tried to install roombapw, it returned "The command '/bin/sh -c npm install' returned a non-zero code: 1"
> 
> Same here - I have HA running on a NUC. "The command '/bin/sh -c npm install' returned a non-zero code: 1"

I forgot to mention that it used to work - I just have a new Roomba i.e. was supprised that it stopped working.

**Comment by jeremywillans** [comment]
This appears to be linked to [this](https://github.com/npm/cli/issues/1832) npm bug.

I have changed the Node Container from Alpine to Boron which has fixed the build issue for me - can you please check?

**Comment by famprinz** [comment]
Don't have time to check if it gets the blid and password but it lets me
install it on HA i.e. its def. better :-)

Will let u know if it all works later this week

**Comment by Rev-777** [comment]
Working now, thanks! That said, I still can't (for the life of me) get rest980 to run with my Roomba. 

When I run the docker run command it returns:

> Error` response from daemon: Conflict. The container name "/rest980" is already in use by container "a1e5badffc105d8735cc2c0247cccf63e9ed6ef2ab5f323db091104a2cd420c3". You have to remove (or rename) that container to be able to reuse that `name.

**Comment by TriskelionTech** [comment]
Got it to install!! so that part works

-- EDIT, was not working, so I posted the log, then realized it was a PEBKAC error... forgot to key in the IP...

Works now!

**Comment by TriskelionTech** [comment]
Correction to my last comment - almost works..

If I deliberately do NOT put the robot in pairing mode, the addon gets a bunch of data from the robot, but if I put the robot in pairing mode, it gets nothing... which sort of makes sense since the robot also disappears from the wifi according to my router, so not sure how the RPI is supposed to see it...

It now gets a large portion of the data, but still shows "Error getting password" at the end...

`> dorita980@3.1.7 getpassword /usr/src/app
> node ./bin/getpassword.js
Make sure your robot is on the Home Base and powered on (green lights on). Then press and hold the HOME button on your robot until it plays a series of tones (about 2 seconds). Release the button and your robot will flash WIFI light.
This step will continue in 10 seconds...
Robot Data:
{ ver: '3',
  hostname: 'iRobot-3383408FB9834645B97EAEDC81428868',
  robotname: 'Mo',
  robotid: '3383408FB9834645B97EAEDC81428868',
  ip: '192.168.1.18',
  mac: '50:14:79:23:04:4D',
  sw: 'lewis+3.12.8+lewis-release-420+10',
  sku: 'i655020',
  nc: 0,
  proto: 'mqtt',
  cap: 
   { binFullDetect: 2,
     dockComm: 1,
     wDevLoc: 2,
     bleDevLoc: 0,
     edge: 0,
     maps: 3,
     pmaps: 5,
     tLine: 2,
     area: 1,
     eco: 1,
     multiPass: 2,
     pose: 1,
     team: 1,
     pp: 0,
     lang: 2,
     '5ghz': 1,
     prov: 3,
     sched: 1,
     svcConf: 1,
     ota: 2,
     log: 2,
     langOta: 0,
     tileScan: 1 },
  blid: '3383408FB9834645B97EAEDC81428868' }
Error getting password. Follow the instructions and try again.`

**Comment by jeremywillans** [comment]
> but if I put the robot in pairing mode, it gets nothing

@ZInventor - make sure your using [this](https://homesupport.irobot.com/app/answers/detail/a_id/8991/~/how-do-i-add-my-wi-fi-connected-robot-to-an-additional-mobile-device-or-phone%3F) paring mode

> When I run the docker run command it returns:

@Rev-777 looks like you already have a container named rest980, delete it first with
- docker stop rest980
- docker container rm rest980

**Comment by TriskelionTech** [comment]
Awesome thanks for the tip about pairing modes, wasn't aware that there was more than one!!

Not that running now but rest980 doesn't seem to want to start?

`> rest980@2.1.0 start /usr/src/app
> node ./bin/www
/usr/src/app/node_modules/dorita980/lib/v2/cloud.js:7
  throw new Error('Not implemented.');
  ^
Error: Not implemented.
    at dorita980 (/usr/src/app/node_modules/dorita980/lib/v2/cloud.js:7:9)
    at new cloud (/usr/src/app/node_modules/dorita980/index.js:12:10)
    at /usr/src/app/routes/api.js:33:46
    at handleIP (/usr/src/app/routes/api.js:26:68)
    at Object.<anonymous> (/usr/src/app/routes/api.js:27:1)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/src/app/app.js:11:16)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/src/app/bin/www:7:11)
    at Module._compile (module.js:577:32)
npm ERR! Linux 5.4.79-v7
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! rest980@2.1.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rest980@2.1.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the rest980 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs rest980
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls rest980
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log`

**Comment by jeremywillans** [comment]
> Not that running now but rest980 doesn't seem to want to start?

@ZInventor - looks like your trying to use the cloud mode? what env variables have you defined?

**Comment by TriskelionTech** [comment]
Currently everything is default hassio raspberry pi image, haven't done any
other config

Zeno LeHéricy

**Comment by TriskelionTech** [comment]
in the rest980 configuration it's just the items that are prompted (blid, password, ip ,and version), not sure where other environment variables are set (not very familiar with linux )

Very strangely, Re-tried it for the 10th time and it worked this time I think, now working on getting the cards and HACS installed

**Comment by jeremywillans** [comment]
yeah thats wierd.. is it failing on initial startup? or are you trying to access a URL and it crashing ?

**Comment by TriskelionTech** [comment]
It was failing on initial startup, but after a ton of tries it all of a sudden didn't throw any errors and stayed running

**Comment by jeremywillans** [comment]
.... never turn it off 🤣

**Comment by TriskelionTech** [comment]
HA! that's the plan now :D Also making a snapshot just in case LOL

**Comment by famprinz** [comment]
Hi,

works fine for me now.

Thanks.

**Comment by jeremywillans** [comment]
Issue closed.
