### ISSUE TITLE
How to see Roomba

### ISSUE THREAD

**Issue by aperezva** [jeremywillans/hass-addons#10]
Hi maybe its a stupid question.

But I installed all the add-ons and I can see the entities, but I don´t know how to see information regwrding Roomba. I configured addons with password an blind, but I don´t know which is the next step to have information from my rooobma.

Any step by step process?

**Comment by jeremywillans** [comment]
Please follow the ha-rest980-roomba repository instructions and post there or on the HA forum if you have issues

**Comment by aperezva** [comment]
Thanks,ç
I have tried several times and to me  it’s not clear, I will try again last time

Thanks why I was asking for help

Thanks again
