### ISSUE TITLE
Lost connection after update to 20220113

### ISSUE THREAD

**Issue by JeroenDeckers** [jeremywillans/hass-addons#13]
After update to version 20220113 i've lost connection to my Roomba.
When going to the url http://xxx.xxx.xxx.xxx:3000/api/local/info/state I only get empty brackets.

{}

What could be the problem?

**Comment by olarodes** [comment]
same!

suppose that php-nginx doesn't work

it said " [WARN  tini (8)] Tini is not running as PID 1 and isn't registered as a child subreaper.
Zombie processes will not be re-parented to Tini, so zombie reaping won't work.
To fix the problem, use the -s option or set the environment variable TINI_SUBREAPER to register Tini as a child subreaper, or run Tini as PID 1."

**Comment by jeremywillans** [comment]
is this still a problem?

**Comment by intentsmatt** [comment]
Hi Jeremy, I don't have this problem with the J7 model.

**Comment by jeremywillans** [comment]
Closed
