### ISSUE TITLE
i7 Password not retrieved with roombapw

### ISSUE THREAD

**Issue by confucius78** [jeremywillans/hass-addons#17]
Getting an error retrieving the pw for firmware 3.

{ ver: '3',
  hostname: 'iRobot-redacted',
  robotname: 'Kimi',
  robotid: 'redacted',
  ip: 'redacted',
  mac: 'redacted',
  sw: 'lewis+22.29.3+2022-08-23-eb90240ea48+Firmware-Build+1832',
  sku: 'i755640',
  nc: 0,
  proto: 'mqtt',
  cap: 
   { binFullDetect: 2,
     oMode: 2,
     dockComm: 1,
     wDevLoc: 2,
     bleDevLoc: 1,
     edge: 0,
     maps: 3,
     pmaps: 10,
     mc: 2,
     tLine: 2,
     area: 1,
     eco: 1,
     multiPass: 2,
     team: 1,
     pp: 0,
     pose: 2,
     lang: 2,
     '5ghz': 1,
     prov: 3,
     sched: 2,
     svcConf: 1,
     ota: 2,
     log: 2,
     langOta: 0,
     ns: 1,
     tileScan: 1 },
  blid: 'redacted' }
Error getting password. Follow the instructions and try again.

**Comment by bobloadmire** [comment]
i actually just had this exact same error with my braava, everything showed except password.

**Comment by jeremywillans** [comment]
robot was correctly in pairing mode?
