### ISSUE TITLE
Add CHANGELOG.md for php-nginx images

### ISSUE THREAD

**Issue by RobertD502** [jeremywillans/hass-addons#21]
Is there any chance you could possibly add a changelog file to both the php-nginx and nginx2 directories?

As of 2024.4, Home Assistant now looks for the changelog file to render the changelogs for Home Assistant add-ons. Since both of these directories are missing the changelog file, it is creating the following error that continues to be logged:

```log
Client error on /addons/39c40414_php-nginx/changelog request 0, message='Attempt to decode JSON with unexpected mimetype: application/octet-stream', url=URL('http://172.30.32.2/addons/39c40414_php-nginx/changelog')
```

The rest980 directories have a changelog and are not causing Home Assistant to raise said error.

**Comment by jeremywillans** [comment]
Should be fixed with latest update
