### ISSUE TITLE
Update not possible

### ISSUE THREAD

**Issue by mwelker79** [jeremywillans/hass-addons#23]
It seems that the update to the latest version 2024057 is not possible.
Error message is attached as a picture 

![image](https://github.com/jeremywillans/hass-addons/assets/18734851/6aa3d7b4-5400-4a5a-b6c4-128b1905e417)

**Comment by jeremywillans** [comment]
Thanks, ive just updated the image tag to a matching version - should now be 8.2.

Please test and advise?

**Comment by mwelker79** [comment]
Great! That fixed the issue.
Thanks for your fast support.

**Comment by jeremywillans** [comment]
Thanks!
