### ISSUE TITLE
Error while installing add-on on supervisor-2021.03.3

### ISSUE THREAD

**Issue by JeroenDeckers** [jeremywillans/hass-addons#3]
Hi i started a new setup with supervisor-2021.03.3.
When installing the rest980 and roombapw add-on I receive the following error.

Failed to install add-on
'NoneType' object has no attribute 'is_file'

**Comment by jeremywillans** [comment]
Per [this](https://community.home-assistant.io/t/supervisor-2021-3-0-local-add-ons-nonetype-object-has-no-attribute-is-file/286350/2) I have added a build.yaml file to each directory.

Can you test and see if this fixes it?

**Comment by JeroenDeckers** [comment]
issue has been solved, i could install the add-on again.
