### ISSUE TITLE
Can't add custom HACS repository

### ISSUE THREAD

**Issue by whasf** [jeremywillans/hass-addons#7]
Hello --

When I try to add your repository I get the following message in HACS:

> Repostitory structure for master is not compliant

I am running HA 2021.6.4, HACS 1.12.4

Thanks!

**Comment by jeremywillans** [comment]
This isnt a HACS Repo, this one needs to be added on the Supervisor as a Third-Party Addon.

[Reference](https://www.home-assistant.io/common-tasks/os#installing-third-party-add-ons)

**Comment by whasf** [comment]
Dang, I saw "HASS" and I thought "HACS". Sorry!
