### ISSUE TITLE
Update to latest dorita980 version

### ISSUE THREAD

**Issue by ajtudela** [jeremywillans/hass-addons#8]
Hi Jeremy, 

I still have some connection issues with my roomba 980. I saw koalazak updated dorita980 adding a timeout in the connection, here: https://github.com/koalazak/dorita980/commit/f4203775ec0bd8f06ab4af7407999938ff115ad7

Could you update the docker image? Maybe that fix my problem.

Thanks

**Comment by jeremywillans** [comment]
That timeout attribute is only as part of the getpassword.js file, not used in the normal running mode of rest980.

I will look to update the files anyway, but i dont think this will help you ☹️

**Comment by ajtudela** [comment]
You're right.

Yesterday, I finally found my issues with the roomba integration. It's related with my amcrest/onvif camera integration. If I disable the camera, the roomba works fine; when I enable the camera, the roomba starts to fail.

**Comment by jeremywillans** [comment]
Bumped to latest dorita980
