### ISSUE TITLE
Issue with roomba map

### ISSUE THREAD

**Issue by rourke750** [jeremywillans/hass-addons#9]
I currently have this set up to work as a hassadon and everything has been working fine for months.  Recently though it has not been generating the clean map.  I noticed my vacuum.log is consistently empty and it looks like the addon-test980 is regenerating the file as root if that matters.  Any idea what I can do to further investigate?

I have been having this issue since novemeber 11.

**Comment by jeremywillans** [comment]
This is currently a known issue with a firmware change done by iRobot.

Tracking in the dorita989 repo [here](https://github.com/koalazak/dorita980/issues/148)
